### ISSUE TITLE
How to adjust the font-size for SRS interface.

### ISSUE THREAD

**Issue by jarodise** [nmartin84/logseq-tokyo-night-theme#4]
Hi, thanks for creating such a great theme, I love it. 

The default font-size is a bit too small for me , I managed to adjust the font-size for the main text area, however, the change is now applied to the SRS cards review interface, I tried to located the CSS selector to adjust it, but somehow couldn't find it. 

Could you kindly show me the right path? thanks!

**Comment by nmartin84** [comment]
So looks like the `:root` element has a `--ls-page-text-size:` property which does affect the SRS text size. I added a variable to my theme that'll allow you to adjust this setting. You can toss this in your custom.css to adjust it on the fly. 1em is the default size, to start off I would suggest small .1 incremental changes to see what works best for you. Just be sure to update your theme from the LS plugin page in order to see the changes.

```
.theme-settings,
html[data-theme=dark], html[data-theme=light] {
  --ts-font-size: 1em;
}
```
